//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountantEntitiesContext : DbContext
    {
        public AccountantEntitiesContext()
            : base("name=AccountantEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<ПодробностиРасчетногоЛиста> ПодробностиРасчетногоЛиста { get; set; }
        public virtual DbSet<РасчетныйЛист> РасчетныйЛист { get; set; }
        public virtual DbSet<УчетСотрудников> УчетСотрудников { get; set; }
    }
}
