//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПодробностиРасчетногоЛиста
    {
        public int Код { get; set; }
        public Nullable<int> КодРасчетногоЛиста { get; set; }
        public string Имя { get; set; }
        public Nullable<int> Сумма { get; set; }
    
        public virtual РасчетныйЛист РасчетныйЛист { get; set; }
    }
}
