//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class РасчетныйЛист
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public РасчетныйЛист()
        {
            this.ПодробностиРасчетногоЛиста = new HashSet<ПодробностиРасчетногоЛиста>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодСотрудника { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Сумма { get; set; }
        public Nullable<int> Дни { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПодробностиРасчетногоЛиста> ПодробностиРасчетногоЛиста { get; set; }
        public virtual УчетСотрудников УчетСотрудников { get; set; }
    }
}
