//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class УчетСотрудников
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public УчетСотрудников()
        {
            this.РасчетныйЛист = new HashSet<РасчетныйЛист>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодДолжности { get; set; }
        public string Фио { get; set; }
        public string Телефон { get; set; }
        public string Пароль { get; set; }
        public bool Статус { get; set; }
    
        public virtual Должность Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РасчетныйЛист> РасчетныйЛист { get; set; }
    }
}
